# .circleci/config.yml
version: 2.1
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:stretch
              environment:
                  IMAGE_NAME: gregumo2/lafougere
        steps:
            - checkout
            - setup_remote_docker

            - run:
                  name: "Build and push Docker image"
                  command: |
                      IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
                      docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                      fi
                      echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                      docker push ${IMAGE_NAME}
    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "5e:5b:c5:83:84:67:3f:60:9c:18:48:e0:56:57:b1:7c"
            - run:
                  name: "Deploy image to production"
                  command: |
                      ssh ${PRODUCTION_SERVER_USER}@${PRODUCTION_SERVER_ADDRESS} -p ${PRODUCTION_SERVER_PORT} "cd ${PRODUCTION_SERVER_PATH} && chmod +x deploy.sh && ./deploy.sh"

workflows:
    version: 2.1
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
